spring:
  application:
    name: easyDoc

  datasource:
    url: "jdbc:mysql://localhost:3306/easy-doc?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      jdbc:
        time_zone: UTC
  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        #mail:
        #host: smtp.mail.yahoo.com
        #port: 587
        #username: ${EMAIL_YAHOO}
        #password: ${EMAIL_YAHOO_APP_PASSWORD}
        #properties:
        #mail:
        #smtp:
        #auth: true
        #starttls:
        #enable: true
      #required: true

      #app:
      #mail:
      #from: ${EMAIL_USERNAME}
  mail:
    host: smtp.office365.com
    port: 587
    username: ${EMAIL_OUTLOOK}
    password: ${EMAIL_OUTLOOK_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
  app:
    mail:
      from: ${EMAIL_OUTLOOK}

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.thymeleaf: DEBUG
    org.attoparser: DEBUG
    rg.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.cache: TRACE
    org.springframework.data.redis.cache: TRACE
    org.springframework.mail: DEBUG